development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://pawpaw.dlib.indiana.edu:8983/fedora
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://pawpaw.dlib.indiana.edu:8983/fedora
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://pawpaw.dlib.indiana.edu:8983/fedora
